# Generated by Django 6.0.1 on 2026-01-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('INFO', 'Info'), ('ASSET_ASSIGNED', 'Asset assigned'), ('TICKET_CREATED', 'Ticket created'), ('TICKET_UPDATED', 'Ticket updated'), ('ASSIGNMENT_RETURNED', 'Assignment returned')], default='INFO', max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
