# Generated by Django 6.0.1 on 2026-02-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('INFO', 'Info'), ('ASSET_ASSIGNED', 'Asset assigned'), ('TICKET_CREATED', 'Ticket created'), ('TICKET_UPDATED', 'Ticket updated'), ('TICKET_RESOLVED', 'Ticket resolved'), ('ASSIGNMENT_RETURNED', 'Assignment returned')], default='INFO', max_length=32),
        ),
    ]
