# Generated by Django 6.0.1 on 2026-02-20 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_repairticket_resolution_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='return_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assignment',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_returned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], default='ASSIGNED', max_length=20),
        ),
    ]
